CREATE TABLE CommonAssessmentTool_Table (
    age INTEGER,
    gender TEXT,
    work_experience INTEGER,
    canada_workex INTEGER,
    dep_num INTEGER,
    canada_born TEXT,
    citizen_status TEXT,
    level_of_schooling TEXT,
    fluent_english TEXT,
    reading_english_scale INTEGER,
    speaking_english_scale INTEGER,
    writing_english_scale INTEGER,
    numeracy_scale INTEGER,
    computer_scale INTEGER,
    transportation_bool TEXT,
    caregiver_bool TEXT,
    housing TEXT,
    income_source TEXT,
    felony_bool TEXT,
    attending_school TEXT,
    currently_employed TEXT,
    substance_use TEXT,
    time_unemployed INTEGER,
    need_mental_health_support_bool TEXT,
    employment_assistance INTEGER,
    life_stabilization INTEGER,
    retention_services INTEGER,
    specialized_services INTEGER,
    employment_related_financial_supports INTEGER,
    employer_financial_supports INTEGER,
    enhanced_referrals INTEGER,
    success_rate INTEGER,
    client_id INTEGER PRIMARY KEY AUTOINCREMENT
);