name: Docker Validation Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize database with data
        run: |
          python initialize_data.py

      - name: Run Tests
        run: |
          python -m pytest tests/

  docker-validate:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t case-management-api .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8000 --name case-management-api case-management-api
          sleep 15  # Wait for container to start

      - name: Test Docker container
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" http://localhost:8080/docs
          docker logs case-management-api

      - name: Print Validation Message
        run: |
          echo "========================"
          echo "✓ Docker image built"
          echo "✓ Container running"
          echo "✓ API accessible"
          echo "✓ Docker validation complete"
          echo "========================"
          echo "Note: This workflow only validates the Docker build."
          echo "Actual deployment to AWS happens when a Release is created."
