name: Python CI Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v5 # Set up Python environment
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install setuptools wheel
          pip install -r requirements.txt  # Install dependencies from requirements.txt
          pip install pylint pytest flake8 black

      - name: Run Code Format Check (Black)
        run: |
          black --check .

      - name: Run Linter Check (Pylint)
        run: |
          pylint $(git ls-files '*.py')

      - name: Run Flake8 Linter
        run: |
          flake8 .

      - name: Initialize database with data
        run: |
          python initialize_data.py  # Initialize database with the required data
          
      - name: Run Tests
        run: |
          python -m pytest tests/

      - name: Print Success Message
        run: |
          echo "CI Pipeline completed successfully!"
          echo "========================"
          echo "✓ Code checked out"
          echo "✓ Python environment set up"
          echo "✓ Dependencies installed"
          echo "✓ Tests executed"
          echo "✓ Linting completed"
          echo "========================"
